# Generated by Django 5.1.4 on 2025-04-17 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0003_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
