# Generated by Django 5.1.4 on 2025-04-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_app', '0014_employee_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='total_salary',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
